name: publish-dinocons
on:
  push:
    branches: [master]
jobs:
  all:
    name: publish-dinocons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish
        uses: mikeal/merge-release@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
